name: Build config files
on:
  push:
    branches:
      - chore/figma-changes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build config
        run: |
          yarn
          yarn build
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update output configs
