name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@master
        name: Bump and Tag Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
